[tool.poetry]
name = "umass-dorm-fider"
version = "0.1.0"
description = ""
authors = ["Leon Ge","Jovy Zhou"]

[tool.poetry.dependencies]
python = ">=3.10.0"
Flask = "^2.2"
Flask-API = "^3.1"
flask-compress = "^1.14"
